blog/urls.py
from django.urls import path, re_path
from blog import views


app_name = 'blog'
urlpatterns = [

    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example: /blog/post/ (same as /blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),

    # Example: /blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example: /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

]

bookmark/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name = "bookmark"
urlpatterns = [
    path("", views.BookmarkLV.as_view(), name ="index"),
    path("<int:pk>/", views.BookmarkDV.as_view(), name="detail"), # genericview 에서는 pk로 받음 .
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config.views import HomeView
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path("bookmark/", include("bookmark.urls")),
    path("blog/", include("blog.urls"))
]

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
# id, title, sluf, decription, content, create_dt , modify_dt

class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField(verbose_name="SLUG", unique=True, allow_unicode=True, help_text="one word for title alias.")
    description = models.CharField("DESCRIPTION", max_length=100, blank=True, help_text="simple text")
    content = models.TextField("CONTENT")
    create_dt = models.DateTimeField("CREATE DATE", auto_now_add=True)
    modify_dt = models.DateTimeField("MODIFY DATE", auto_now=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = "posts"
        db_table = 'blog_posts'
        ordering = ('-modify_dt',)
    
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))
    def get_previous(self):
        return self.get_previous_by_modify_dt()
    def get_next(self):
        return self.get_next_by_modify_dt()

bookmark/models.py
from django.db import models

# Create your models here.
# title, url

class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank =True) # 최대길이 100, 공백허용 TRUE
    url = models.URLField('URL', unique=True)
    def __str__(self):
        return self.title + " " + self.url

blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic import DayArchiveView, TodayArchiveView

from blog.models import Post


#--- ListView
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2


#--- DetailView
class PostDV(DetailView):
    model = Post
    template_name = "blog/post_archive.html"


#--- ArchiveView
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'
    template_name = "blog/post_archive.html"
    


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True
    template_name = "blog/post_archive_year.html"

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'
    template_name = "blog/post_archive_month.html"


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'
    template_name = "blog/post_archive_day.html"


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'
    template_name = "blog/post_archive_.html"

bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark
# Create your views here.

class BookmarkLV(ListView):
    model = Bookmark

    # template_name="bookmark/bookmark_list.html" #appname/model_name_list.html
    # context_object_name = "object_list" # object_list
class BookmarkDV(DetailView):
    model = Bookmark

    # template_name = 'bookmark/bookmark_detail.html'
    # context_object_name = "object" # object

config/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name="home.html"

blog/templates/blog/post_all.html
<h1>BLOG POST LIST</h1>
<br>
{% for post in posts %}
<h3><a href={% url 'blog:post_detail' post.slug %}>{{post.title}}</a> </h3>
{# <h3><a href="{{post.get_absolute_url}}">{{post.title}}</a> </h3> #}
{{post.modify_dt | date:"Y년 N d일" }}
<p>{{post.content}}</p>
{% endfor %}

<br>

<div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
        {% endif %}
    </span>

</div>

blog/templates/blog/post_archive.html
<h1>Archive List {% now "Y m d" %}</h1>

<ul>
    {% for date in date_list %}
    <li style="display: inline;"><a href="{% url 'blog:post_year_archive' date|date:'Y' %}"> Year-{{date|date:'Y'}} </a></li>
    {% endfor %}
</ul>

<br>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{post.modify_dt | date:"Y-m-d"}}
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
        </li>
        {% endfor %}
    </ul>
</div>

{{date_list}}

{{object_list}}

blog/templates/blog/post_archive_day.html
<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

blog/templates/blog/post_archive_month.html
<h1>Post Archives for {{ month|date:"N, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

blog/templates/blog/post_archive_year.html
<h1>Post Archives for {{year|date:"Y"}}</h1>


<ul>
    {% for date in date_list %}
    <li style="display: inline;"><a href="{% url 'blog:post_month_archive' date|date:'Y' date|date:'b'%}"> Year-{{date|date:'F'}}</a></li>
    {% endfor %}
</ul>

{# m : 04, F : April, M : Apr, b : apr #}

<br>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{post.modify_dt | date:"Y-m-d"}}
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
        </li>
        {% endfor %}
    </ul>
</div>

{{date_list}}
{{object_list}}

blog/templates/blog/post_detail.html
<h2>{{ object.title }}</h2>

<p>
    {% if object.get_previous %}
    <a href="{{ object.get_previous.get_absolute_url }}" title="View previous post">
        &laquo;-- {{ object.get_previous }}
    </a>
    {% endif %}

    {% if object.get_next %}
    | <a href="{{ object.get_next.get_absolute_url }}" title="View next post">
    {{ object.get_next }} --&raquo;
    </a>
    {% endif %}
</p>

<p>{{ object.modify_dt|date:"j F Y" }}</p>
<br>

<div>
    {{ object.content|linebreaks }}
</div>

bookmark/templates/bookmark/bookmark_detail.html
<h3>TITLE: {{object.title}}</h3>

<h5>URL : <a href="{{object.url}}"> {{object.url}}</a></h5>

bookmark/templates/bookmark/bookmark_list.html
<h1>Bookmark List</h1>

<br>

<ul>
    {% for bookmark in object_list %}
    <li><a href ="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark.title }}</a></li>
    {% endfor %}
</ul>

templates/home.html
<h1>우리의 블로그</h1>